/* Contenido ÚNICO de la página, en español e inglés. Se actualizó con la hoja de vida del 3 de octubre de 2026.
   Solo cambian los textos: la estructura (listas de 4 capacidades, 2 experiencias, 3 proyectos, etc.) se mantiene para no mover el diseño. */
window.CV = {
  es: {
    nombre: 'Juan Sebastián Pulido Bojacá',
    rol: 'Soporte técnico y desarrollo web, con foco en front-end',
    sub: 'Tecnólogo en Análisis y Desarrollo de Software · Bogotá, Colombia',
    lema: 'Hago que la tecnología funcione para las personas. Y cuando no existe la solución, la construyo.',
    perfil: 'Tecnólogo en Análisis y Desarrollo de Software con experiencia en soporte técnico de nivel 1: atención de tickets bajo SLA y seguimiento de cada caso hasta su cierre. Desarrollo aplicaciones web completas, tanto en front-end como en back-end, con diversos lenguajes y herramientas, y me especializo en el front-end: interfaces interactivas, limpias y de gran impacto visual, construidas con atención al detalle y al diseño.',
    nav: { hacer: 'Qué hago', exp: 'Experiencia', proy: 'Proyectos', ia: 'IA aplicada', stack: 'Herramientas', contacto: 'Contacto' },
    cta1: 'Ver proyectos', cta2: 'Descargar HV',
    hacerTitulo: 'Qué hago',
    hacer: [
      ['Soporte N1', 'Atención de tickets sobre aplicativos y sistemas, de forma remota y presencial, bajo SLA y con seguimiento hasta el cierre.'],
      ['Front-end e interfaces', 'Interfaces interactivas y de gran impacto visual con HTML, CSS, JavaScript, TypeScript y React.'],
      ['Back-end y datos', 'Desarrollo de CRUD, APIs y bases de datos con Node.js, Express, Python, Django, PostgreSQL y SQL.'],
      ['Calidad y documentación', 'Validación funcional, pruebas y documentación clara que facilitan el uso y el mantenimiento de cada solución.'],
    ],
    expTitulo: 'Experiencia',
    exp: [
      ['Group COS (BPO · IPO)', 'Aprendiz SENA · Soporte técnico N1 y gestión de soluciones tecnológicas', 'Nov 2025 – Abr 2026', 'Atendí tickets de soporte de nivel 1 sobre aplicativos y sistemas internos, de forma remota y presencial, en Jira y Azure DevOps y bajo SLA, escalando a desarrollo y QA. Apoyé sistemas de visualización de métricas en Power BI y documenté procedimientos y soluciones.'],
      ['World Games', 'Administrador · Atención al cliente y operación', 'Feb 2022 – Nov 2023', 'Administré el establecimiento de productos tecnológicos, consolas y videojuegos: caja y finanzas, atención y asesoría a clientes, ventas, control de inventario y reposición.'],
    ],
    proyTitulo: 'Proyectos',
    proyIntro: 'Cuatro soluciones completas, cada una en su isla del mapa.',
    proyVenta: 'Soy un desarrollador orientado a soluciones y a la atención a la interfaz y al diseño: cada proyecto parte de un problema real y termina en una interfaz clara, cuidada y agradable de usar.',
    proy: [
      { n: '01', nombre: 'Servicios Kairos', tipo: 'Sistema de ventas e inventario a la medida · cliente real', links: [['Demo en vivo', 'https://pulise222.github.io/kairos-gestion-demo/']], nota: 'Repositorio privado: es el sistema de un cliente real. La demo usa datos de ejemplo.',
        resumen: 'Mejoré los procesos de un establecimiento comercial con un sistema de ventas e inventario a la medida, que les dio mejor manejo de las finanzas y de la información, desde el levantamiento de requerimientos hasta la implementación.',
        puntos: ['CRUD de productos, venta por monto con sumas, cierre de caja con cuadre y control de inventario', 'Copias de seguridad y respaldo diario en Excel', 'Diseño con identidad propia: logo, paleta y modo claro y oscuro'],
        datos: [['370+', 'pruebas automáticas'], ['39', 'comprobaciones en navegador'], ['7', 'secciones de productos']], tec: 'CRUD · React · TypeScript · Node.js · PostgreSQL' },
      { n: '02', nombre: 'Nivel', tipo: 'Sistema de ventas, inventario y ganancias', links: [['GitHub', 'https://github.com/pulise222/nivel-gestion-negocio'], ['Demo en vivo', 'https://pulise222.github.io/nivel-gestion-negocio-demo/']],
        resumen: 'Un sistema adaptable a cualquier establecimiento: a partir del registro de productos e inventarios genera dashboards y apoya el manejo, la trazabilidad y las finanzas del negocio.',
        puntos: ['CRUD de productos, proveedores y usuarios, con roles y permisos validados en el servidor', 'Trazabilidad de cada movimiento de inventario y dinero en pesos enteros', 'Copias de seguridad automáticas y manual de usuario'],
        datos: [['2', 'roles de usuario'], ['0', 'dinero con decimales'], ['100%', 'sin internet']], tec: 'CRUD · React · TypeScript · Node.js · PostgreSQL' },
      { n: '03', nombre: 'Jardín Sullivan', tipo: 'Mi proyecto · solución web de gestión', links: [['GitHub', 'https://github.com/pulise222/jardin-sullivan-gestion-crud'], ['Demo en vivo', 'https://pulise222.github.io/jardin-sullivan-demo/']],
        resumen: 'Una web con CRUD completo para mejorar la administración de los datos y la comunicación de un jardín infantil: tres perfiles de usuario (administrador, profesor y acudiente) para gestionar asistencia, evaluación y boletines trimestrales, desde el análisis de necesidades hasta su implementación.',
        puntos: ['CRUD completo de estudiantes, cursos, materias, asistencia y evaluaciones', 'Información organizada y documentada para su uso y mantenimiento', 'Interfaz dinámica y adaptable al celular, con identidad propia'],
        datos: [['CRUD', 'gestión completa de datos']], tec: 'CRUD · React · Vite · Django · SQL' },
      { n: '04', nombre: 'Portafolio web interactivo', tipo: 'Mi hoja de vida en línea · proyecto propio', links: [['Ver portafolio', 'https://pulise222.github.io/cv-web/'], ['GitHub', 'https://github.com/pulise222/cv-web']],
        resumen: 'Diseñé y desarrollé mi hoja de vida como una experiencia interactiva: un mapa en 3D que se recorre con el scroll, con modo claro y oscuro, en español e inglés y adaptable al celular.',
        puntos: ['Diseño de interfaces y animación ligada al scroll', 'Despliegue automático con GitHub Pages y GitHub Actions', 'Presentación limpia, actual y fácil de explorar'],
        datos: [['3D', 'mapa interactivo'], ['2', 'idiomas']], tec: 'HTML · CSS · JavaScript · Three.js' },
    ],
    iaTitulo: 'IA aplicada, con criterio',
    iaIntro: 'La IA escribe rápido; el valor está en saber qué pedir, cómo comprobarlo y cuándo decir que no.',
    ia: [
      ['Dirijo', 'Defino el problema y las reglas antes de pedir nada.'],
      ['Verifico', 'Nada está listo hasta probarlo: pruebas automáticas y revisión en el navegador.'],
      ['Corrijo', 'Detecto errores y los hago arreglar, no los acepto a ciegas.'],
      ['Documento', 'Manuales, guías de instalación y casos de prueba.'],
    ],
    stackTitulo: 'Herramientas',
    stack: [['Soporte y análisis', ['Jira', 'Azure DevOps', 'Power BI', 'Notion', 'Excel', 'SQL']], ['Desarrollo', ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL']], ['IA', ['ChatGPT', 'Claude', 'Gemini']]],
    estudios: ['Tecnólogo en Análisis y Desarrollo de Software · SENA · 2024 – 2026', 'Bachiller Académico con énfasis en Ingeniería · I.E.D. Atanasio Girardot · 2018'],
    idiomas: 'Español nativo · Inglés B2',
    contactoTitulo: 'Hablemos', contactoTexto: 'Si tu equipo necesita a alguien que atienda, valide y también construya, escríbeme.',
    correo: 'jpulidobojaca@gmail.com', telefono: '311 856 6722', github: 'https://github.com/pulise222',
  },
  en: {
    nombre: 'Juan Sebastián Pulido Bojacá',
    rol: 'Technical support and web development, front-end focused',
    sub: 'Software Analysis and Development Technologist · Bogotá, Colombia',
    lema: 'I make technology work for people. And when the solution does not exist, I build it.',
    perfil: 'Software Analysis and Development Technologist with level 1 technical support experience: handling tickets under SLA and following each case through to closure. I build complete web applications on both the front end and the back end, with a range of languages and tools, and I specialize in the front end: interactive, clean interfaces with strong visual impact, crafted with attention to detail and design.',
    nav: { hacer: 'What I do', exp: 'Experience', proy: 'Projects', ia: 'Applied AI', stack: 'Tools', contacto: 'Contact' },
    cta1: 'See projects', cta2: 'Download CV',
    hacerTitulo: 'What I do',
    hacer: [
      ['Level 1 support', 'Handling of tickets on applications and systems, remotely and on site, under SLA and followed through to closure.'],
      ['Front end & interfaces', 'Interactive interfaces with strong visual impact, built with HTML, CSS, JavaScript, TypeScript and React.'],
      ['Back end & data', 'Development of CRUD, APIs and databases with Node.js, Express, Python, Django, PostgreSQL and SQL.'],
      ['Quality & documentation', 'Functional validation, testing and clear documentation that make each solution easy to use and maintain.'],
    ],
    expTitulo: 'Experience',
    exp: [
      ['Group COS (BPO · IPO)', 'SENA Apprentice · Level 1 technical support and technology solutions management', 'Nov 2025 – Apr 2026', 'I handled level 1 support tickets on internal applications and systems, remotely and on site, in Jira and Azure DevOps and under SLA, escalating to development and QA. I supported metrics visualization systems in Power BI and documented procedures and solutions.'],
      ['World Games', 'Manager · Customer service and operations', 'Feb 2022 – Nov 2023', 'I managed a store of technology products, consoles and video games: cash and finances, customer service and advice, sales, inventory control and restocking.'],
    ],
    proyTitulo: 'Projects',
    proyIntro: 'Four complete solutions, each on its own island of the map.',
    proyVenta: 'I am a solutions-oriented developer who cares about the interface and the design: every project starts from a real problem and ends in a clear, polished and pleasant-to-use interface.',
    proy: [
      { n: '01', nombre: 'Servicios Kairos', tipo: 'Custom sales and inventory system · real client', links: [['Live demo', 'https://pulise222.github.io/kairos-gestion-demo/']], nota: 'Private repository: it is a real client’s system. The demo uses sample data.',
        resumen: 'I improved the processes of a retail business with a custom sales and inventory system that gave them better control of their finances and information, from requirements gathering to implementation.',
        puntos: ['CRUD of products, sales by amount with sums, cash closing with reconciliation and inventory control', 'Backups and a daily Excel copy', 'Design with its own identity: logo, palette and light and dark mode'],
        datos: [['370+', 'automated tests'], ['39', 'browser checks'], ['7', 'product sections']], tec: 'CRUD · React · TypeScript · Node.js · PostgreSQL' },
      { n: '02', nombre: 'Nivel', tipo: 'Sales, inventory and profit system', links: [['GitHub', 'https://github.com/pulise222/nivel-gestion-negocio'], ['Live demo', 'https://pulise222.github.io/nivel-gestion-negocio-demo/']],
        resumen: 'A system adaptable to any business: from the registration of products and inventory it generates dashboards and supports the management, traceability and finances of the business.',
        puntos: ['CRUD of products, suppliers and users, with roles and permissions validated on the server', 'Traceability of every inventory movement and money in whole pesos', 'Automatic backups and a user manual'],
        datos: [['2', 'user roles'], ['0', 'money with decimals'], ['100%', 'offline']], tec: 'CRUD · React · TypeScript · Node.js · PostgreSQL' },
      { n: '03', nombre: 'Jardín Sullivan', tipo: 'My project · web management solution', links: [['GitHub', 'https://github.com/pulise222/jardin-sullivan-gestion-crud'], ['Live demo', 'https://pulise222.github.io/jardin-sullivan-demo/']],
        resumen: 'A web app with full CRUD to improve a kindergarten’s data management and communication: three user profiles (administrator, teacher and guardian) to manage attendance, assessment and quarterly report cards, from needs analysis to implementation.',
        puntos: ['Full CRUD of students, courses, subjects, attendance and assessments', 'Information organized and documented for use and maintenance', 'Dynamic, mobile-friendly interface with its own identity'],
        datos: [['CRUD', 'full data management']], tec: 'CRUD · React · Vite · Django · SQL' },
      { n: '04', nombre: 'Interactive web portfolio', tipo: 'My online CV · own project', links: [['View portfolio', 'https://pulise222.github.io/cv-web/'], ['GitHub', 'https://github.com/pulise222/cv-web']],
        resumen: 'I designed and built my CV as an interactive experience: a 3D map explored with scrolling, with light and dark mode, in Spanish and English and mobile-friendly.',
        puntos: ['Interface design and scroll-linked animation', 'Automatic deployment with GitHub Pages and GitHub Actions', 'Clean, modern presentation that is easy to explore'],
        datos: [['3D', 'interactive map'], ['2', 'languages']], tec: 'HTML · CSS · JavaScript · Three.js' },
    ],
    iaTitulo: 'Applied AI, with judgement',
    iaIntro: 'AI writes fast; the value is in knowing what to ask, how to check it and when to say no.',
    ia: [
      ['I direct', 'I define the problem and the rules before asking for anything.'],
      ['I verify', 'Nothing is done until tested: automated tests and browser review.'],
      ['I correct', 'I spot mistakes and have them fixed instead of accepting blindly.'],
      ['I document', 'Manuals, installation guides and test cases.'],
    ],
    stackTitulo: 'Tools',
    stack: [['Support & analysis', ['Jira', 'Azure DevOps', 'Power BI', 'Notion', 'Excel', 'SQL']], ['Development', ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL']], ['AI', ['ChatGPT', 'Claude', 'Gemini']]],
    estudios: ['Software Analysis and Development Technologist · SENA · 2024 – 2026', 'Academic High School Diploma, Engineering focus · I.E.D. Atanasio Girardot · 2018'],
    idiomas: 'Spanish native · English B2',
    contactoTitulo: 'Let’s talk', contactoTexto: 'If your team needs someone who supports, validates and also builds, write to me.',
    correo: 'jpulidobojaca@gmail.com', telefono: '311 856 6722', github: 'https://github.com/pulise222',
  },
}

/* Cambio de idioma compartido: guarda la elección y vuelve a pintar. */
window.idiomaInicial = () => { try { return localStorage.getItem('cv-idioma') || (navigator.language.startsWith('en') ? 'en' : 'es') } catch { return 'es' } }
window.guardarIdioma = (i) => { try { localStorage.setItem('cv-idioma', i) } catch {} }
