/* Contenido ÚNICO de la página, en español e inglés. Las tres maquetas lo leen de aquí,
   así comparas SOLO el diseño. Todo sale de la hoja de vida y de los proyectos reales. */
window.CV = {
  es: {
    nombre: 'Juan Sebastián Pulido Bojacá',
    rol: 'Analista de soporte y soluciones tecnológicas',
    sub: 'Tecnólogo en Análisis y Desarrollo de Software · Bogotá, Colombia',
    lema: 'Hago que la tecnología funcione para las personas. Y cuando no existe la solución, la construyo.',
    perfil: 'Acompaño a usuarios y equipos técnicos para que los sistemas funcionen: atiendo y hago seguimiento a incidentes, valido funcionalidades, documento soluciones y coordino con desarrollo y QA. Mi diferencial es que también construyo: he desarrollado sistemas completos para negocios reales, así que entiendo el problema desde el usuario hasta el código.',
    nav: { hacer: 'Qué hago', exp: 'Experiencia', proy: 'Proyectos', ia: 'IA aplicada', stack: 'Herramientas', contacto: 'Contacto' },
    cta1: 'Ver proyectos', cta2: 'Descargar HV',
    hacerTitulo: 'Qué hago',
    hacer: [
      ['Soporte y seguimiento', 'Atiendo incidentes y requerimientos, los diagnostico y les doy seguimiento hasta cerrarlos.'],
      ['Validación funcional', 'Compruebo que cada solución haga lo que se espera, con datos y casos reales, antes de implementarla.'],
      ['Documentación', 'Dejo procedimientos y soluciones escritos para que cualquiera pueda consultarlos y continuarlos.'],
      ['Coordinación técnica', 'Hablo el idioma del usuario y el del equipo de desarrollo y QA para que se entiendan.'],
    ],
    expTitulo: 'Experiencia',
    exp: [
      ['Group COS (BPO · IPO)', 'Aprendiz SENA · Soporte y gestión de soluciones tecnológicas', 'Nov 2025 – Abr 2026', 'Gestión y seguimiento de necesidades, validación de soluciones con APIs, datos y formularios, coordinación con desarrollo y QA, y documentación en Azure DevOps, Notion, Figma y Power BI.'],
      ['World Games', 'Administrador · Atención al cliente y operación', 'Sector comercial y tecnológico', 'Atención directa, seguimiento de solicitudes, control de inventario y manejo de situaciones bajo presión en una tienda de consolas y videojuegos.'],
    ],
    proyTitulo: 'Proyectos',
    proyIntro: 'Soluciones completas que diseñé, probé y documenté.',
    proy: [
      { n: '01', nombre: 'Servicios Kairos', tipo: 'Sistema a la medida para un cliente real', links: [], nota: 'Repositorio privado: es el sistema de un cliente real. Disponible para mostrar en entrevista.',
        resumen: 'Insumos de calzado vendían con un cuaderno. Escuché cómo trabajaban y construí un sistema que una persona mayor, usando un computador por primera vez, pudiera manejar sola.',
        puntos: ['Venta por monto con sumas, cierre de caja y copias de seguridad', 'Letra ajustable y guía en pantalla para la usuaria mayor', 'Manual de usuario en PDF y piloto de una semana con feedback'],
        datos: [['370+', 'pruebas automáticas'], ['39', 'comprobaciones en navegador'], ['7', 'secciones de productos']], tec: 'React · TypeScript · Node · PostgreSQL' },
      { n: '02', nombre: 'Nivel', tipo: 'Sistema de ventas, inventario y ganancias', links: [['GitHub', 'https://github.com/pulise222/nivel-gestion-negocio'], ['Demo en vivo', 'https://pulise222.github.io/nivel-gestion-negocio-demo/']],
        resumen: 'Un sistema completo para tiendas pequeñas que funciona sin internet y se instala en un solo computador. Incluye una demo pública en línea.',
        puntos: ['Roles con permisos verificados en el servidor', 'Inventario auditable: cada cambio deja rastro', 'Copias de seguridad reales y manual de usuario'],
        datos: [['2', 'roles de usuario'], ['0', 'dinero con decimales'], ['100%', 'sin internet']], tec: 'React · Express · Prisma · PostgreSQL' },
      { n: '03', nombre: 'Jardín Sullivan', tipo: 'Mi proyecto · sitio y gestión de un jardín infantil', links: [['GitHub', 'https://github.com/pulise222/jardin-sullivan-gestion-crud']],
        resumen: 'Solución web para un jardín infantil, desarrollada durante mi formación en el SENA. Es mi proyecto: levanté las necesidades, diseñé la interfaz a color y construí sus funciones.',
        puntos: ['Análisis de necesidades y diseño visual completo', 'Interfaz a color, pensada para celular', 'Pruebas y documentación para su uso y mantenimiento'],
        datos: [['1°', 'proyecto propio'], ['100%', 'de principio a fin']], tec: 'HTML · CSS · React · Django' },
    ],
    iaTitulo: 'IA aplicada, con criterio',
    iaIntro: 'La IA escribe rápido; el valor está en saber qué pedir, cómo comprobarlo y cuándo decir que no.',
    ia: [
      ['Dirijo', 'Defino el problema y las reglas antes de pedir nada.'],
      ['Verifico', 'Nada está listo hasta probarlo: pruebas automáticas y revisión en el navegador.'],
      ['Corrijo', 'Detecto errores y los hago arreglar, no los acepto a ciegas.'],
      ['Documento', 'Manuales, guías de instalación y casos de prueba.'],
    ],
    stackTitulo: 'Herramientas',
    stack: [['Soporte y análisis', ['Azure DevOps', 'Power BI', 'Notion', 'Figma', 'Excel', 'SQL']], ['Desarrollo', ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL']], ['IA', ['Asistentes de código', 'Automatización', 'Análisis y documentación']]],
    estudios: ['Tecnólogo en Análisis y Desarrollo de Software · SENA · 2026', 'Bachiller Académico con énfasis en Ingeniería · 2018'],
    idiomas: 'Español nativo · Inglés B2',
    contactoTitulo: 'Hablemos', contactoTexto: 'Si tu equipo necesita a alguien que atienda, valide y también construya, escríbeme.',
    correo: 'jpulidobojaca@gmail.com', github: 'https://github.com/pulise222',
  },
  en: {
    nombre: 'Juan Sebastián Pulido Bojacá',
    rol: 'Technical support & solutions analyst',
    sub: 'Software Analysis and Development Technologist · Bogotá, Colombia',
    lema: 'I make technology work for people. And when the solution does not exist, I build it.',
    perfil: 'I work with users and technical teams to keep systems running: I handle and follow up on incidents, validate features, document solutions and coordinate with development and QA. What sets me apart is that I also build: I have developed complete systems for real businesses, so I understand the problem from the user all the way to the code.',
    nav: { hacer: 'What I do', exp: 'Experience', proy: 'Projects', ia: 'Applied AI', stack: 'Tools', contacto: 'Contact' },
    cta1: 'See projects', cta2: 'Download CV',
    hacerTitulo: 'What I do',
    hacer: [
      ['Support & follow-up', 'I handle incidents and requests, diagnose them and follow up until they are closed.'],
      ['Functional validation', 'I check that every solution does what is expected, using real data and cases, before it goes live.'],
      ['Documentation', 'I leave procedures and solutions written down so anyone can consult and continue them.'],
      ['Technical coordination', 'I speak the user’s language and the development and QA team’s, so they understand each other.'],
    ],
    expTitulo: 'Experience',
    exp: [
      ['Group COS (BPO · IPO)', 'SENA Apprentice · Support and technology solutions management', 'Nov 2025 – Apr 2026', 'Managing and tracking needs, validating solutions involving APIs, data and forms, coordinating with development and QA, and documenting in Azure DevOps, Notion, Figma and Power BI.'],
      ['World Games', 'Manager · Customer service and operations', 'Retail and technology', 'Direct customer service, request follow-up, inventory control and handling pressure in a console and video game store.'],
    ],
    proyTitulo: 'Projects',
    proyIntro: 'Complete solutions that I designed, tested and documented.',
    proy: [
      { n: '01', nombre: 'Servicios Kairos', tipo: 'Custom system for a real client', links: [], nota: 'Private repository: it is a real client’s system. Available to show in an interview.',
        resumen: 'A footwear supplies business was selling with a paper notebook. I listened to how they worked and built a system that an older person, using a computer for the first time, could run alone.',
        puntos: ['Sales by amount with sums, cash closing and backups', 'Adjustable text size and on-screen guide for the older user', 'PDF user manual and a one-week pilot with feedback'],
        datos: [['370+', 'automated tests'], ['39', 'browser checks'], ['7', 'product sections']], tec: 'React · TypeScript · Node · PostgreSQL' },
      { n: '02', nombre: 'Nivel', tipo: 'Sales, inventory and profit system', links: [['GitHub', 'https://github.com/pulise222/nivel-gestion-negocio'], ['Live demo', 'https://pulise222.github.io/nivel-gestion-negocio-demo/']],
        resumen: 'A complete system for small shops that works offline and installs on a single computer. It includes a public online demo.',
        puntos: ['Roles with permissions enforced on the server', 'Auditable inventory: every change leaves a trace', 'Real backups and a user manual'],
        datos: [['2', 'user roles'], ['0', 'money with decimals'], ['100%', 'offline']], tec: 'React · Express · Prisma · PostgreSQL' },
      { n: '03', nombre: 'Jardín Sullivan', tipo: 'My project · website and management for a kindergarten', links: [['GitHub', 'https://github.com/pulise222/jardin-sullivan-gestion-crud']],
        resumen: 'Web solution for a kindergarten, developed during my SENA training. It is my project: I gathered the needs, designed the interface in colour and built its features.',
        puntos: ['Needs analysis and complete visual design', 'Colourful interface, designed for mobile', 'Testing and documentation for use and maintenance'],
        datos: [['1st', 'own project'], ['100%', 'start to finish']], tec: 'HTML · CSS · React · Django' },
    ],
    iaTitulo: 'Applied AI, with judgement',
    iaIntro: 'AI writes fast; the value is in knowing what to ask, how to check it and when to say no.',
    ia: [
      ['I direct', 'I define the problem and the rules before asking for anything.'],
      ['I verify', 'Nothing is done until tested: automated tests and browser review.'],
      ['I correct', 'I spot mistakes and have them fixed instead of accepting blindly.'],
      ['I document', 'Manuals, installation guides and test cases.'],
    ],
    stackTitulo: 'Tools',
    stack: [['Support & analysis', ['Azure DevOps', 'Power BI', 'Notion', 'Figma', 'Excel', 'SQL']], ['Development', ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL']], ['AI', ['Coding assistants', 'Automation', 'Analysis & documentation']]],
    estudios: ['Software Analysis and Development Technologist · SENA · 2026', 'Academic High School Diploma, Engineering focus · 2018'],
    idiomas: 'Spanish native · English B2',
    contactoTitulo: 'Let’s talk', contactoTexto: 'If your team needs someone who supports, validates and also builds, write to me.',
    correo: 'jpulidobojaca@gmail.com', github: 'https://github.com/pulise222',
  },
}

/* Cambio de idioma compartido: guarda la elección y vuelve a pintar. */
window.idiomaInicial = () => { try { return localStorage.getItem('cv-idioma') || (navigator.language.startsWith('en') ? 'en' : 'es') } catch { return 'es' } }
window.guardarIdioma = (i) => { try { localStorage.setItem('cv-idioma', i) } catch {} }
